#!/usr/bin/env bash
set -e

pip install -r requirements.txt

# Generate .streamlit/secrets.toml from Render environment variables.
# This file is not committed to the repo; it is created fresh on each deploy.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$SCRIPT_DIR/.streamlit"
cat > "$SCRIPT_DIR/.streamlit/secrets.toml" << EOF
# Auto-generated by render_build.sh — do not edit manually

# Mistral AI Configuration
mistral_key = "$mistral_key"

# Anthropic Configuration
anthropic_key = "$anthropic_key"

# Agent IDs
bme_agent = "$bme_agent"
bme_agent_library = "$bme_agent_library"

# File paths
default_instructions_dir = "agent_files/instructions"
default_documents_dir = "agent_files/documents"
default_activity_dir = "agent_files/activity_descriptions"

# App
app_password = "$app_password"

# Baserow
baserow_api_url = "$baserow_api_url"
baserow_api_token = "$baserow_api_token"
EOF

echo "secrets.toml written to: $SCRIPT_DIR/.streamlit/secrets.toml"
ls -la "$SCRIPT_DIR/.streamlit/"
