services:
  - type: web
    name: bme-agent
    runtime: python
    buildCommand: bash render_build.sh
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: MISTRAL_KEY
        sync: false
      - key: ANTHROPIC_KEY
        sync: false
      - key: BME_AGENT
        sync: false
      - key: BME_AGENT_LIBRARY
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: BASEROW_API_URL
        sync: false
      - key: BASEROW_API_TOKEN
        sync: false
