#!/usr/bin/env bash
set -e

pip install -r requirements.txt

# Generate .streamlit/secrets.toml from Render environment variables.
# This file is not committed to the repo; it is created fresh on each deploy.
mkdir -p .streamlit
cat > .streamlit/secrets.toml << EOF
# Auto-generated by render_build.sh — do not edit manually

# Mistral AI Configuration
mistral_key = "$MISTRAL_KEY"

# Anthropic Configuration
anthropic_key = "$ANTHROPIC_KEY"

# Agent IDs
bme_agent = "$BME_AGENT"
bme_agent_library = "$BME_AGENT_LIBRARY"

# File paths
default_instructions_dir = "agent_files/instructions"
default_documents_dir = "agent_files/documents"
default_activity_dir = "agent_files/activity_descriptions"

# App
app_password = "$APP_PASSWORD"

# Baserow
baserow_api_url = "$BASEROW_API_URL"
baserow_api_token = "$BASEROW_API_TOKEN"
EOF

echo "secrets.toml written successfully"
