#!/usr/bin/env bash
set -e

# Generate .streamlit/secrets.toml from Railway environment variables.
# This file is not committed to the repo; it is created fresh on each deploy.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mkdir -p "$SCRIPT_DIR/.streamlit"
cat > "$SCRIPT_DIR/.streamlit/secrets.toml" << EOF
# Auto-generated by start.sh — do not edit manually

# Mistral AI Configuration
MISTRAL_KEY = "$MISTRAL_KEY"

# Anthropic Configuration
ANTHROPIC_KEY = "$ANTHROPIC_KEY"

# Agent IDs
BME_AGENT = "$BME_AGENT"
BME_AGENT_LIBRARY = "$BME_AGENT_LIBRARY"

# File paths
DEFAULT_INSTRUCTIONS_DIR = "agent_files/instructions"
DEFAULT_DOCUMENTS_DIR = "agent_files/documents"
DEFAULT_ACTIVITY_DIR = "agent_files/activity_descriptions"

# App
APP_PASSWORD = "$APP_PASSWORD"

# Postgres (provided by Railway)
DATABASE_URL = "$DATABASE_URL"
EOF

echo "secrets.toml written to: $SCRIPT_DIR/.streamlit/"

streamlit run app.py --server.port "${PORT:-8501}" --server.address 0.0.0.0
