#!/usr/bin/env bash
set -e

# Generate .streamlit/secrets.toml from Railway environment variables.
# This file is not committed to the repo; it is created fresh on each deploy.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
mkdir -p "$SCRIPT_DIR/.streamlit"
cat > "$SCRIPT_DIR/.streamlit/secrets.toml" << EOF
# Auto-generated by start.sh — do not edit manually

# Postgres (provided by Railway)
DATABASE_URL = "$DATABASE_URL"
EOF

echo "secrets.toml written to: $SCRIPT_DIR/.streamlit/"

cd "$SCRIPT_DIR"
export PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}"
exec streamlit run app.py --server.port "${PORT:-8501}" --server.address 0.0.0.0
