"""
File registry for Anthropic Files API.

Maps each document filename to its current Anthropic file_id along with the
title + description from agent_files/documents/manifest.toml. Generated by
script_configure_agents.py — do not edit by hand.

Shape:
    {
        "robot_details.md": {
            "file_id":     "file_011...",
            "title":       "mBot Robot — Hardware, Setup, ...",
            "description": "Hardware specs (ports, sensors, motors), ..."
        },
        ...
    }
"""

import json
import os

registry_path = os.path.join(os.path.dirname(__file__), "file_registry.json")


def save(file_map: dict):
    """Write the document→metadata mapping to the registry."""
    with open(registry_path, "w") as f:
        json.dump(file_map, f, indent=2)


def load() -> dict:
    """Return the document→metadata mapping, or {} if the registry is missing."""
    if not os.path.exists(registry_path):
        return {}
    with open(registry_path) as f:
        return json.load(f)
