"""
File registry for Anthropic Files API.
Maps document names to their current file_ids in the workspace.
Generated by script_configure_anthropic.py — do not edit by hand.
"""

import json
import os
from typing import Optional

registry_path = os.path.join(os.path.dirname(__file__), "file_registry.json")


def save(file_map: dict):
    """Write document→file_id mapping to the registry."""
    with open(registry_path, "w") as f:
        json.dump(file_map, f, indent=2)


def load() -> dict:
    """Return the full document→file_id mapping, or {} if registry doesn't exist."""
    if not os.path.exists(registry_path):
        return {}
    with open(registry_path) as f:
        return json.load(f)


def get_file_id(document_name: str) -> Optional[str]:
    """Look up the file_id for a document by name. Returns None if not found."""
    return load().get(document_name)


def all_file_ids() -> list:
    """Return all registered file_ids as a list."""
    return list(load().values())
